version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "11:45"
      timezone: Australia/Melbourne
    allow:
      - dependency-name: "*"
        dependency-type: "production"
    open-pull-requests-limit: 10
